name: 'maxc test typescript action'
description: 'Provide a description here'
author: '@mcascone'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'
  my-input:
    description:
      'Another input description. Will be appended with "from inside"'
    required: true

# Define your outputs here.
outputs:
  time:
    description: 'the time after the wait'
  my-output:
    description: 'the output of the action'

runs:
  using: node20
  main: dist/index.js
